### ISSUE TITLE
bzip2

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Storage#11]
Why are we using the slowest compression method ? Really really slow . Like 4-8mb/s with luck .
Can you change it to something else ? Anything special about this type of compression ?

```
Algorithm     Compressed size        Compression          Decompression

lzop           398MB    20.8%      4.2s    455.6MB/s     3.1s    617.3MB/s
lz4            416MB    21.7%      4.5s    424.2MB/s     1.6s   1181.3MB/s
brotli (q0)    307MB    16.1%      7.3s    262.1MB/s     4.9s    390.5MB/s
brotli (q1)    234MB    12.2%      8.7s    220.0MB/s     4.9s    390.5MB/s
zstd           266MB    13.9%     11.9s    161.1MB/s     3.5s    539.5MB/s
pigz (x4)      232MB    12.1%     13.1s    146.1MB/s     4.2s    455.6MB/s
gzip           232MB    12.1%     39.1s     48.9MB/s     9.2s    208.0MB/s
lbzip2 (x4)    188MB     9.9%     42.0s     45.6MB/s    13.2s    144.9MB/s
pbzip2 (x4)    189MB     9.9%    117.5s     16.3MB/s    20.1s     95.2MB/s
bzip2          189MB     9.9%    273.4s      7.0MB/s    42.8s     44.7MB/s
pixz (x4)      132MB     6.9%    456.3s      4.2MB/s     7.9s    242.2MB/s
xz             132MB     6.9%   1027.8s      1.9MB/s    17.3s    110.6MB/s
brotli (q11)   141MB     7.4%   4979.2s      0.4MB/s     3.6s    531.6MB/s
```
https://serverfault.com/questions/872749/bzip2-too-slow-multiple-cores-are-avaible

No matter how much compression we use , the file-size will not decrease .

**Comment by DanielnetoDotCom** [comment]
what do you think will be the best format?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Why aren't you using the same as HLS ? the php-zip ?

**Comment by akhilleusuggo** [comment]
I think that you don't realize the issue with your configuration !

1- The video does encode 
2- The video is zipped and sent to the streamer site .
3- The video does unzip
4- The video is zipped once again with bzip2 compression 
5- The video is starting to be sent to YPT-Storage
6- The video is has started to be unzipped on YPT-Storage

Is this all necessary ? Huge wast of time and resources .

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

I'm reopening this ,because this is madness . I mean rly .
Long streams takes longer to transfer than to encode ...

Can you change this type of compression ?? Why the HLS is transfered to streamer site with php-zip and from streamer to storage with gzip2 ?

**Comment by DanielnetoDotCom** [comment]
Agree, as long as I finish the project I am engaged in now, I will review this process.

**Comment by akhilleusuggo** [comment]
btw pigz is the best I've found , but I don't know how it manages the permissions . Can't confirm ( but uses multi-threading compression )

**Comment by DanielnetoDotCom** [comment]
pigz looks a good option, I will research about it.

**Comment by akhilleusuggo** [comment]
Hello after half of a year. Since I got tired of this compression ratio and wait time, I decided to take a look at the code for once. I though that is was hardcoded on the plugin, but it seems it's just a letter that was killing my patience. 

I'm personally using pigz , but I'm not pushing since users must first install it ( you'll need to add it on description of the plugin, and error log ). `sudo apt-get install pigz ` . For now only gzip ( 1 core usage , but ~8 times faster than bzip2

**Comment by DanielnetoDotCom** [comment]
Question, does pigz also create a .tgz file?

for example can I use pigz to compress and tar to decompress?

**Comment by DanielnetoDotCom** [comment]
I found this 
![image](https://user-images.githubusercontent.com/18009293/117678375-b592de00-b185-11eb-9ec9-dea48bbf50ac.png)

what do you think?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom The one that I use is much simple this ;

$cmd = "tar -c --use-compress-program=pigz -f {$backupFile} -C {$backupDir} .";

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

> maybe if we compress a 10 GB file and the storages are in a different network a compression worth.

I'm not sure Daniel if you ever tested it. There's no compression. `.ts` files doesn't support compression
Example a folder of hls `res720` = 1gb  ; when you compress it it's = 1gb

Live example; 

```
$ du -h res720/
767M	res720/

$ tar -c --use-compress-program=pigz -f res720.tgz -C res720/ .

du -h res720.tgz 
767M	res720.tgz
```

As you can see, we saved literally 0 mbs

Give it a try , and you will understand what I mean. We're wasting a lot of resources for nothing.

**Comment by akhilleusuggo** [comment]
Yes. That's why I've asked if you're using a specific line to decompress the tar, so I could test it and debug.

**Comment by DanielnetoDotCom** [comment]
That is all we have

![image](https://user-images.githubusercontent.com/18009293/117973746-23b0df80-b303-11eb-8c0f-e6009bf2c21c.png)

I will remove the compress options from all commands, I guess it will improve a lot

**Comment by DanielnetoDotCom** [comment]
I sent updates to YPTStorage server and plugin

**Comment by akhilleusuggo** [comment]
That should do it. 
So , I'll start testing once I can change the code locally

> I will remove the compress options from all commands, I guess it will improve a lot

In my case improvement from bzip to no compression was over x80-100 times. Was compression at 5-10mb/s , now 550mb/s
