### ISSUE TITLE
Update Disk Usage ;

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Storage#12]
When I update disk usage , does not report the right usage . For some reason does it multiple times . Those are the logs of after 1 click on disk update usage .

```
[30/Jun/2020:08:52:54 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_HD.mp4 HTTP/1.1" 200 3646 "-" "-"
[30/Jun/2020:08:52:59 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_Low.mp4 HTTP/1.1" 200 3645 "-" "-"
[30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_SD.mp4 HTTP/1.1" 200 3645 "-" "-"
[30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_HD.mp4 HTTP/1.1" 200 3646 "-" "-"
[30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_Low.mp4 HTTP/1.1" 200 3645 "-" "-"
[30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_SD.mp4 HTTP/1.1" 200 3645 "-" "-"
[30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_HD.mp4 HTTP/1.1" 200 3646 "-" "-"
[30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_Low.mp4 HTTP/1.1" 200 3645 "-" "-"
[30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_SD.mp4 HTTP/1.1" 200 3645 "-" "-"
 [30/Jun/2020:08:53:01 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_HD.mp4 HTTP/1.1" 200 3646 "-" "-"
```

File size shown on MyVideos section : 
![image](https://user-images.githubusercontent.com/52116577/86106438-3a728d00-bac9-11ea-9e48-d84a894f2fc6.png)

Real file size : 
![image](https://user-images.githubusercontent.com/52116577/86106619-73126680-bac9-11ea-91db-ddcb38d94cb4.png)

**Comment by DanielnetoDotCom** [comment]
this is really strange.
does it happen every time you click on it? or just some times.
I was not able to reproduce it here.

**Comment by akhilleusuggo** [comment]
everytime .
I mean this gonna be an issue for many people who's planning to get the DiskQuota plugin .

**Comment by DanielnetoDotCom** [comment]
Agree this is wrong, I just cannot see how is it happening.

is it a video hosted in the storage?

the same happens with local videos?

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom happens much more on storage site then the local site .
I mean right now , all my storage site is wrong . Everything indicates x2 x3 more size then it is .

I'm not sure if this is caused by the dump files on the streamer site .

**Comment by DanielnetoDotCom** [comment]
It will count the dummy files, but it supposes to be only 10 bytes each.
also count the images, and zip files if they were not deleted.
can you please check if it deletes the zip files?

I mean it will count anything with the video "filename" form database

**Comment by akhilleusuggo** [comment]
![image](https://user-images.githubusercontent.com/52116577/86468905-0acdba00-bd41-11ea-9032-a31be76a109b.png)

**Comment by DanielnetoDotCom** [comment]
can you please make something like this in your streamer and storage

`ls -lah /var/www/html/YouPHPTube/videos/_ID.81107179*`

**Comment by akhilleusuggo** [comment]
STORAGE SITE : 
![image](https://user-images.githubusercontent.com/52116577/86469567-56cd2e80-bd42-11ea-8e92-fdd90c06f736.png)

STREAMER SITE: 

![image](https://user-images.githubusercontent.com/52116577/86469774-c80ce180-bd42-11ea-9068-44ff206ec79d.png)

**Comment by DanielnetoDotCom** [comment]
Ok, all looks perfect, so if you click on the "update disk storage" it will give you the wrong size?

![image](https://user-images.githubusercontent.com/18009293/86469931-c6c2c100-bd10-11ea-9aca-78bfd9edb2d9.png)

**Comment by akhilleusuggo** [comment]
Yes Sir

**Comment by DanielnetoDotCom** [comment]
> ef852e370b841.68237251_HD.mp4 HTTP/1.1" 200 3646 "-" "-"
> [30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_Low.mp4 HTTP/1.1" 200 3645 "-" "-"
> [30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_SD.mp4 HTTP/1.1" 200 3645 "-" "-"
> [30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_HD.mp4 HTTP/1.1" 200 3646 "-" "-"
> [30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_Low.mp4 HTTP/1.1" 200 3645 "-" "-"
> [30/Jun/2020:08:53:00 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_SD.mp4 HTTP/1.1" 200 3645 "-" "-"
>  [30/Jun/2020:08:53:01 +0000] "HEAD /videos/_YPTuniqid_5ef852e370b841.68237251_HD.mp4 HTTP/1.1" 200 3646 "

Is this log from storage or streamer?

Could you detect if is the streamer that is requesting multiple times or is the storage that is processing multiple times?

**Comment by DanielnetoDotCom** [comment]
I will fix, I could reproduce it here

**Comment by akhilleusuggo** [comment]
Hello Daniel , on the streamer site , too many requests are made that looks like inspecting the header 

```
[03-Jul-2020 15:38:29 Europe/Helsinki] AVideoLog::DEBUG: getUsageFromURL: start (https://storage.example.com/videos/_ID.68237251_HD.mp4)
[03-Jul-2020 15:38:29 Europe/Helsinki] AVideoLog::DEBUG: getUsageFromURL: curl_init 
[03-Jul-2020 15:38:29 Europe/Helsinki] AVideoLog::DEBUG: getUsageFromURL: response header HTTP/1.1 200 OK
Date: Fri, 03 Jul 2020 12:38:29 GMT
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: 46545649a030c1c8227=srpekdqtov1654654654jt0vj6; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: max-age=1, private, must-revalidate
Pragma: no-cache
Set-Cookie: 79f9a78441fe287987930c1c8227=srpekdqtov16543219b7jt0vj6; path=/
Access-Control-Allow-Origin: *
Last-Modified: Mon, 29 Jun 2020 13:49:14 GMT
ETag: "11b31ec4e-fb8a80"
Content-Length: 4751223886
Content-Type: video/mp4
```

I don't wanna past here all the log , but you got the idea , just too many of this requests of header .

**Comment by DanielnetoDotCom** [comment]
Please try this update on the Streamer site

**Comment by akhilleusuggo** [comment]
Works for me , but php updateDiskUsage not working .
Nor 
![image](https://user-images.githubusercontent.com/52116577/86480325-7bcb9c80-bd56-11ea-8956-0620e5f08a02.png)

**Comment by akhilleusuggo** [comment]
When running `php updateDiskUsage`
on /install directory 

![image](https://user-images.githubusercontent.com/52116577/86480481-c0efce80-bd56-11ea-941a-bd376565373c.png)

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Daniel , I have to delete everyday handreds of this times . Can you send a fix ? Maybe they should be on /tmp directory and not on the` /object` directory or `/install `
