### ISSUE TITLE
Add up storage to my YPT

### ISSUE THREAD

**Issue by HESSEBO** [WWBN/AVideo-Storage#16]
Hi, I have a question please !
I added an extra storage to my YPT site so that to extend the size of hosting using YPT storage plugin, but I can't get it working. I mounted the drive inside the website folder in the but still no luck. can somebody guide me with some useful information and what configurations need to be done so that my HDD appears as extended storage on my website. 

thanks

**Comment by DanielnetoDotCom** [comment]
basically, you need another webserver to be your YPTStorage

The idea is to be a complete another server, not on the same, but maybe you can create a virtual host into this new drive

**Comment by akhilleusuggo** [comment]
Mount the drive on /var/www/html/new_drive
on the new drive git clone the AVideo-Storage
Now on the vhost , point it to /var/www/html/new_drive/AVideo-Storage 

This should work , because I'm using it on my home-lab and no issues .

**Comment by HESSEBO** [comment]
> Mount the drive on /var/www/html/new_drive
> on the new drive git clone the AVideo-Storage
> Now on the vhost , point it to /var/www/html/new_drive/AVideo-Storage
> 
> This should work , because I'm using it on my home-lab and no issues .

It worked like a charm (^_^)
Thank you very much.
