### ISSUE TITLE
Where is a pricing page for the storage and CDN?

### ISSUE THREAD

**Issue by JoshWho** [WWBN/AVideo-Storage#32]
I need to use HLS and looking for your pricing plans what are cost wise.

**Comment by JoshWho** [comment]
Ok I am getting to green light to try this What All do I need to get started with this so we can use the HLS

**Comment by JoshWho** [comment]
Do I need the YPT STorage plugin?

**Comment by DanielnetoDotCom** [comment]
it does not need any extra plugin

the only thing is, you cannot use Backblaze and CDN storage at the same time. 
if you want to use our storage you will need to transfer the backblaze back to your site and upload it again to the CDN storage


if you load the 10 USD, I can configure it for you.

**Comment by JoshWho** [comment]
Do you have that script to reload the videos back to the site from Backblaze?

**Comment by DanielnetoDotCom** [comment]
I will do it for you if you want to move to the CDN storage

**Comment by JoshWho** [comment]
Ok kewl Let me get 10 on there.

**Comment by JoshWho** [comment]
Ok Just added $10.00 to it.

**Comment by JoshWho** [comment]
New uploads are breaking, do I need to change the settings around in Custom Advance?

**Comment by JoshWho** [comment]
Nevermind maybe it was taking a while to still upload to the storage.
