### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Storage#5]
So if my streaming site has 20-30Gb , and each storage 1TB let's say . The streaming site acts like a DNS for each storage site ?
And how the plugins FTP and AWS works ? Does the streaming site has to download the files to share them to the viewers ? Or does it act as a link to the FTP storage ? 
I mean the bandwidth , where is consumed from ? The streaming site or the FTP server ?
Thanks

**Comment by DanielnetoDotCom** [comment]
> So if my streaming site has 20-30Gb , and each storage 1TB let's say . The streaming site acts like a DNS for each storage site ?

I am not sure what you mean about "DNS for each Storage" but your streamer site will decide to what storage send the video

> And how the plugins FTP and AWS works ? Does the streaming site has to download the files to share them to the viewers ? Or does it act as a link to the FTP storage ?

FTP and AWS has only one storage, with the AVideo-Storage you can have multiple storages

> I mean the bandwidth , where is consumed from ? The streaming site or the FTP server ?

it will consume the bandwidth form FTP or S3 or Storage, in other words it will NOT consume the bandwidth from the Streamer

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom 

> So if my streaming site has 20-30Gb , and each storage 1TB let's say . The streaming site acts like a DNS for each storage site ?
> 
> I am not sure what you mean about "DNS for each Storage" but your streamer site will decide to what storage send the video
My question is : Asuming the video is located in storage1.example.com . The streamer site is example.com , so the streamer site ( example.com ) , gonna act like a DNS-link to the storage site ( storage.example.com ) . The viewers doesn't know that they're connected to storage.example.com but example.com 
So the streamer site are doing anything but redirect the viewers to the file location . Is that correct ?
Does it require a DB ? Or it does share the same DB with the streamer site ?

Thanks for the answers

**Comment by DanielnetoDotCom** [comment]
yes you are correct

the storage does not need a DB, it will use the streamer Webservice
