### ISSUE TITLE
img

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Storage#7]
I see that only the videos are moved to a different server .
Is there anyway to use this script to move img/webp/gifs to a storage server dedicated only for the img/webp/gifs . This will improve a lot the speed of the server / IO .

I have the main server with 120GB Nvem SSD , and the Database is doing great , but at some point may reach the limit .

That's why I was wondering if there's anyway to move img/webp/gifs to another server/directory .
This same script/plugin could have this option

**Comment by DanielnetoDotCom** [comment]
we do not have this option yet. 

but usually, images consume a low space.

**Comment by akhilleusuggo** [comment]
on my secondary site , I have 42k img . Is not about space only but IO .
It was just an idea , but that may need API . Thanks anyway , just a feedback .
