### ISSUE TITLE
transfer problems 

### ISSUE THREAD

**Issue by akhilleusuggo** [WWBN/AVideo-Storage#8]
when there's a transfer between servers , the compressed files ( HLS ) , does not get deleted after the transfer , not the videos's folders are deleted .

I've just moved all the videos to Local , and when checking ths Storage site : 

![image](https://user-images.githubusercontent.com/52116577/82680463-f7fd9b00-9c54-11ea-8a34-10c26ddfc4c0.png)

![image](https://user-images.githubusercontent.com/52116577/82680602-31cea180-9c55-11ea-9319-5eab9f57defc.png)

The deleteOrphanFiles.php does not help

**Comment by DanielnetoDotCom** [comment]
This is when you transfer from...

1. streamer to storage?
2. storage to streamer?
3. storage to storage?

**Comment by akhilleusuggo** [comment]
this specific issue from Storage to Streamer ( local )

**Comment by DanielnetoDotCom** [comment]
I just sent an update, you also will need to update the storage plugin.

**Comment by akhilleusuggo** [comment]
Thank you. I'll try it on the week-end for a bulk transfer .

**Comment by akhilleusuggo** [comment]
I'll close this for the moment .
