### ISSUE TITLE
I can't move video to new storage

### ISSUE THREAD

**Issue by zauklian** [WWBN/AVideo-Storage#9]
I got the following error log.

PHP Fatal error:  Uncaught Error: Call to undefined function _error_log() in /var/www/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code:659
Stack trace:
#0 /var/www/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code(530): YPTStorage::log(77, 'Start (Local to...')
#1 /var/www/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code(725): YPTStorage::moveFromLocalToSite(77, '2')
#2 /var/www/AVideo/plugin/AVideoPlugin.php(506): YPTStorage->afterNewVideo(77)
#3 /var/www/AVideo/objects/aVideoEncoderNotifyIsDone.json.php(58): AVideoPlugin::afterNewVideo(77)
#4 {main}
  thrown in /var/www/AVideo/plugin/YPTStorage/YPTStorage.php(14) : eval()'d code(1) : eval()'d code on line 659

**Comment by DanielnetoDotCom** [comment]
Hi

maybe you are using a wrong version of AVideo

can you please confirm what version are you using?

**Comment by zauklian** [comment]
> 
> 
> Hi
> 
> maybe you are using a wrong version of AVideo
> 
> can you please confirm what version are you using?

AVideo version 8.0

**Comment by akhilleusuggo** [comment]
we're at 8.9

**Comment by zauklian** [comment]
> 
> 
> we're at 8.9

Upgrade to version 8.9 and then work fine.

Thanks :)
